/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Helper.CRUD;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author riza
 */
public class Laporan extends javax.swing.JFrame {

    /**
     * Creates new form Laporan
     */
    private int pemasukan = 0;
    private int pengeluaran = 0;
    private int sampahBeli;
    private int sampahJual;
    private int keuntungan;
    private double saldo;
    private int nJual;
    private int nBeli;

    private int bulan;
    private String tahun;

    CRUD db;

    public Laporan() {
        if (!Main.restriced) {
            JOptionPane.showMessageDialog(null, "Please run from main class");
            System.exit(0);
        }
        initComponents();
        db = new CRUD();
    }

    private String validasi() {
        if (combBulan.getSelectedIndex() == 0) {
            return "Masukan bulan!";
        }
        if (combTahun.getSelectedIndex() == 0) {
            return "Masukan tahun!";
        }

        bulan = combBulan.getSelectedIndex();
        tahun = combTahun.getSelectedItem().toString();
        return null;
    }

    private String formatCurr(double d) {
        if (d >= 0) {
            return String.format("Rp, %,.0f", d).replace(",", ".") + ",-";
        } else {
            return String.format("- Rp. %,.0f", d * -1).replace(",", ".") + ",-";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        combBulan = new javax.swing.JComboBox<>();
        combTahun = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLaporan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 96, 100));

        combBulan.setBackground(new java.awt.Color(255, 255, 255));
        combBulan.setForeground(new java.awt.Color(0, 96, 100));
        combBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Bulan--", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember", " " }));

        combTahun.setBackground(new java.awt.Color(255, 255, 255));
        combTahun.setForeground(new java.awt.Color(0, 96, 100));
        combTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Tahun--", "2017", " " }));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/bitcoin-presentation-with-reporter (2).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Laporan Bulanan");

        btnOk.setBackground(new java.awt.Color(255, 255, 255));
        btnOk.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnOk.setForeground(new java.awt.Color(0, 96, 100));
        btnOk.setText("Pratinjau");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 96, 100));
        jButton2.setText("iReport");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(17, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(combBulan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(combTahun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(combBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(combTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        tableLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Total Pemasukan", ""},
                {"Total Pengeluaran", null},
                {"Total Sampah Terbeli", null},
                {"Total Sampah Terjual", null},
                {"Total Saldo", null},
                {"Total Kentungan", null},
                {"Jumlah Transaksi Jual", null},
                {"Jumlah Transaksi Beli", null}
            },
            new String [] {
                "Variabel", "Total"
            }
        ));
        jScrollPane1.setViewportView(tableLaporan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        String msg = validasi();
        if (msg == null) {
            try {
                String col = "pemasukan";
                String tab = "administrasi";
                String where = "MONTH( tanggal ) =" + bulan + " AND YEAR( tanggal ) =" + tahun + "";
                db.get(col, tab, where, -1);

                ResultSet res = db.getResult();

                while (res.next()) {
                    int p = res.getInt(1);
                    if (p > 0) {
                        pemasukan += p;
                    } else {
                        pengeluaran += p;
                    }
                }
                tableLaporan.setValueAt(formatCurr(pemasukan), 0, 1);
                tableLaporan.setValueAt(formatCurr(pengeluaran * -1), 1, 1);
                tableLaporan.setValueAt(formatCurr(pengeluaran + pemasukan), 5, 1);
                db.closeConnection();

                col = "SUM(berat_total), COUNT(*)";
                tab = "transaksi_jual";

                db.get(col, tab, where, -1);
                res = db.getResult();
                if (res.next()) {
                    sampahJual = res.getInt(1);
                    nJual = res.getInt(2);
                    tableLaporan.setValueAt(sampahJual + " Kg", 3, 1);
                    tableLaporan.setValueAt(nJual, 6, 1);
                }
                db.closeConnection();

                tab = "transaksi_beli";

                db.get(col, tab, where, -1);
                res = db.getResult();
                if (res.next()) {
                    sampahBeli = res.getInt(1);
                    nBeli = res.getInt(2);
                    tableLaporan.setValueAt(sampahBeli + " Kg", 2, 1);
                    tableLaporan.setValueAt(nBeli, 7, 1);
                }
                db.closeConnection();

                String query = "SELECT saldo FROM administrasi ORDER BY id_adm DESC LIMIT 1";
                db.query(query);
                res = db.getResult();
                if (res.next()) {
                    saldo = res.getDouble(1);
                    tableLaporan.setValueAt(formatCurr(saldo), 4, 1);
                }

            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            } finally {
                pemasukan = 0;
                pengeluaran = 0;
            }

        } else {
            JOptionPane.showMessageDialog(null, msg);
        }
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox<String> combBulan;
    private javax.swing.JComboBox<String> combTahun;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableLaporan;
    // End of variables declaration//GEN-END:variables
}
